server:
  port: 0

spring:
  application:
    name: catalog
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

