services:
  postgresDb:
    image: postgres:latest
    command: postgres -c 'max_connections=100'
    restart: always
    ports:
      - 5451:5432
    environment:
      POSTGRES_DB: devlet
      POSTGRES_PASSWORD: nDqQ7b3VcbvmAmHjWDhB
      POSTGRES_USER: postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"
