server:
  port: 8765

spring:
  application:
    name: devlet-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka


